#!/bin/bash
# Karpathy 神经网络课程 - 批量导入 Notebook LLM 脚本
# 使用方法: ./import-karpathy-to-notebooklm.sh

set -e

PLAYLIST_URL="https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ"
OUTPUT_DIR="./karpathy-neural-networks"
mkdir -p "$OUTPUT_DIR"

echo "🎬 正在处理 Karpathy - Neural Networks: Zero to Hero"
echo "================================================"

# 检查依赖
command -v yt-dlp >/dev/null 2>&1 || {
    echo "❌ 需要安装 yt-dlp"
    echo "   Mac: brew install yt-dlp"
    echo "   Linux: curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o ~/.local/bin/yt-dlp && chmod +x ~/.local/bin/yt-dlp"
    exit 1
}

# 方法1: 下载所有视频字幕 (推荐)
echo "📥 方法1: 下载所有字幕文件..."
yt-dlp \
    --write-auto-sub \
    --skip-download \
    --sub-langs en \
    --yes-playlist \
    --output "$OUTPUT_DIR/%(playlist_index)02d - %(title)s.%(ext)s" \
    "$PLAYLIST_URL" 2>&1 | tee "$OUTPUT_DIR/download.log"

echo ""
echo "✅ 字幕下载完成！"
echo ""

# 方法2: 提取视频清单
echo "📋 方法2: 生成视频清单..."
yt-dlp \
    --flat-playlist \
    --print "%(playlist_index)s. %(title)s" \
    --print "%(webpage_url)s" \
    "$PLAYLIST_URL" > "$OUTPUT_DIR/video-list.txt"

echo "📄 视频清单已保存: $OUTPUT_DIR/video-list.txt"
echo ""

# 方法3: 合并所有字幕为 Notebook LM 格式
echo "📚 方法3: 合并为 Notebook LM 格式..."

cat > "$OUTPUT_DIR/README.md" << 'EOF'
# Neural Networks: Zero to Hero - Andrej Karpathy

> 本课程由前 Tesla AI 总监、OpenAI 创始成员 Andrej Karpathy 主讲
> 从0开始构建神经网络，深入理解大语言模型原理

## 课程列表

EOF

# 添加视频列表到 README
yt-dlp \
    --flat-playlist \
    --print "- [%(title)s](%(webpage_url)s)" \
    "$PLAYLIST_URL" >> "$OUTPUT_DIR/README.md"

cat >> "$OUTPUT_DIR/README.md" << 'EOF'

## 使用方法

### 导入 Notebook LLM

1. 打开 https://notebooklm.google.com
2. 创建新 Notebook
3. 点击「+」添加 Source
4. 选择上传文件，上传 `.srt` 或 `.vtt` 字幕文件
5. 或使用 YouTube 链接直接导入

### 文件说明

- `*.srt` / `*.vtt` - 视频字幕文件（可直接导入 Notebook LLM）
- `video-list.txt` - 视频链接清单
- `README.md` - 课程目录

## 学习建议

1. **按顺序观看** - 课程由浅入深，建议从第1集开始
2. **动手实践** - 配合 GitHub 代码仓库一起练习
3. **做笔记** - 使用 Notebook LLM 的问答功能深化理解

---
Generated by OpenClaw Assistant
EOF

echo "✅ 完成！"
echo ""
echo "📁 输出目录: $OUTPUT_DIR"
echo ""
echo "📋 文件列表:"
ls -la "$OUTPUT_DIR"
echo ""
echo "🚀 下一步:"
echo "   1. 打开 https://notebooklm.google.com"
echo "   2. 创建新 Notebook"
echo "   3. 上传 $OUTPUT_DIR 中的 .srt 字幕文件"
echo ""
