#!/usr/bin/env python3
"""
Karpathy 神经网络课程 - 字幕提取工具
无需 yt-dlp，使用 youtube-transcript-api
"""

import json
import os
from pathlib import Path

# 播放列表视频ID列表 (Neural Networks: Zero to Hero)
PLAYLIST_VIDEOS = [
    {
        "id": "VMj-3S1tku0",
        "title": "The spelled-out intro to neural networks and backpropagation: building micrograd",
        "index": 1
    },
    {
        "id": "PaCmpygFfXo", 
        "title": "The spelled-out intro to language modeling: building makemore",
        "index": 2
    },
    {
        "id": "TCH_1BHY58I",
        "title": "Building makemore Part 2: MLP",
        "index": 3
    },
    {
        "id": "P6sfmUTpLmc",
        "title": "Building makemore Part 3: Activations & Gradients, BatchNorm",
        "index": 4
    },
    {
        "id": "t3YJ5hKiMQ0",
        "title": "Building makemore Part 4: Becoming a Backprop Ninja",
        "index": 5
    },
    {
        "id": "q8SA3rM6ckI",
        "title": "Building makemore Part 5: Building WaveNet",
        "index": 6
    },
    {
        "id": "kCc8FmEb1nY",
        "title": "Let's build GPT: from scratch, in code, spelled out",
        "index": 7
    },
    {
        "id": "bZQun8Y4L2A",
        "title": "State of GPT | BRK216HFS",
        "index": 8
    },
    {
        "id": "zjkBMFhNj_g",
        "title": "Deep Dive into LLMs like ChatGPT",
        "index": 9
    }
]

def create_notebooklm_import():
    """创建 Notebook LLM 导入文件"""
    
    output_dir = Path("./karpathy-neural-networks")
    output_dir.mkdir(exist_ok=True)
    
    # 创建主文档
    main_doc = output_dir / "karpathy-course-all.md"
    
    with open(main_doc, 'w', encoding='utf-8') as f:
        f.write("# Neural Networks: Zero to Hero\n")
        f.write("\n")
        f.write("> Andrej Karpathy 主讲\n")
        f.write("> 从0开始构建神经网络，深入理解大语言模型原理\n")
        f.write("\n")
        f.write("---\n\n")
        
        for video in PLAYLIST_VIDEOS:
            f.write(f"## {video['index']}. {video['title']}\n")
            f.write(f"\n")
            f.write(f"**YouTube链接:** https://www.youtube.com/watch?v={video['id']}\n")
            f.write(f"\n")
            f.write(f"**字幕:** [点击下载](https://downsub.com/?url=https://www.youtube.com/watch?v={video['id']})\n")
            f.write(f"\n")
            f.write(f"<!-- 字幕内容将在这里插入 -->\n")
            f.write(f"\n")
            f.write("---\n\n")
    
    print(f"✅ 已创建: {main_doc}")
    
    # 创建视频清单 JSON
    playlist_json = output_dir / "playlist.json"
    with open(playlist_json, 'w', encoding='utf-8') as f:
        json.dump({
            "title": "Neural Networks: Zero to Hero",
            "instructor": "Andrej Karpathy",
            "videos": PLAYLIST_VIDEOS
        }, f, indent=2, ensure_ascii=False)
    
    print(f"✅ 已创建: {playlist_json}")
    
    # 创建 README
    readme = output_dir / "README.md"
    with open(readme, 'w', encoding='utf-8') as f:
        f.write("# Karpathy - Neural Networks: Zero to Hero\n\n")
        f.write("## 📺 课程导入 Notebook LLM 指南\n\n")
        f.write("### 方法1: 逐个导入 (推荐)\n\n")
        f.write("1. 访问 https://notebooklm.google.com\n")
        f.write("2. 创建新 Notebook\n")
        f.write("3. 点击 **+** → **YouTube**\n")
        f.write("4. 粘贴视频链接:\n\n")
        
        for video in PLAYLIST_VIDEOS:
            f.write(f"   - {video['title']}\n")
            f.write(f"     `https://www.youtube.com/watch?v={video['id']}`\n\n")
        
        f.write("\n")
        f.write("### 方法2: 批量下载字幕后导入\n\n")
        f.write("```bash\n")
        f.write("# 使用 yt-dlp 下载所有字幕\n")
        f.write("yt-dlp --write-auto-sub --skip-download --sub-langs en \\\n")
        f.write("  --yes-playlist \\\n")
        f.write('  -o "%(playlist_index)02d - %(title)s.%(ext)s" \\\n')
        f.write('  "https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ"\n')
        f.write("```\n\n")
        f.write("然后上传 `.srt` 文件到 Notebook LLM\n\n")
        
        f.write("### 方法3: 使用第三方工具\n\n")
        f.write("| 工具 | 网址 | 说明 |\n")
        f.write("|:---|:---|:---|\n")
        f.write("| DownSub | downsub.com | 粘贴链接下载字幕 |\n")
        f.write("| YouTube Transcript | 浏览器插件 | 一键复制字幕 |\n")
        f.write("| NoteGPT | notegpt.io | AI总结+导出 |\n\n")
        
        f.write("## 📚 课程大纲\n\n")
        for video in PLAYLIST_VIDEOS:
            f.write(f"{video['index']}. [{video['title']}](https://www.youtube.com/watch?v={video['id']})\n")
        
        f.write("\n")
        f.write("## 💡 学习建议\n\n")
        f.write("1. **按顺序学习** - 课程由浅入深\n")
        f.write("2. **动手实践** - 配合代码仓库练习\n")
        f.write("3. **善用 Notebook LLM** - 问答、总结、关联概念\n\n")
        f.write("---\n")
        f.write("Generated by OpenClaw Assistant\n")
    
    print(f"✅ 已创建: {readme}")
    print(f"\n📁 所有文件保存在: {output_dir.absolute()}")

if __name__ == "__main__":
    create_notebooklm_import()
